### ISSUE TITLE
The startup question

### ISSUE THREAD

**Issue by Nekoer** [YabaiNyan/nhentai-json-http-server#1]
The following problem occurs when I start up with node njhs.Js
![c4 2 8eni 84m1 n u 8p](https://user-images.githubusercontent.com/32485369/53023559-6f63de00-3498-11e9-9335-2016e7b33550.png)
The test environment was Centos 7.2

**Comment by YabaiNyan** [comment]
Huh, that seems to be an issue with the nhentai-js library. I'm looking into it.

**Comment by YabaiNyan** [comment]
@Nekoer Could you provide a `node -v`? might be an issue with the "positive lookbehind" feature used at the start (`?<=`).

(lookbehind support was added node version >6.0.0)

**Comment by otakurisu** [comment]
![9yh m15p2 ki 0 0 _hj9p](https://user-images.githubusercontent.com/32485369/53294212-3f606600-381d-11e9-8a57-fb3499570f93.png)

**Comment by YabaiNyan** [comment]
@Nekoer it's not enabled by default until node v7.0.0

Either update to a newer node version or try ` node --harmony njhs.js`

**Comment by YabaiNyan** [comment]
@Nekoer 
Hi have you tested `--harmony`? I'd like to mark this issue as solved :)
你试了`--harmony`吗？我想把这个问题标记为已解决了:)

**Comment by otakurisu** [comment]
`--harmony` was very useful and I can now use the API properly

**Comment by YabaiNyan** [comment]
@Nekoer Cool!
